### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by JRDNBLFRT**
@LukeBogTools

### CODE REVIEW

**Comment by JohnBogTools** [comment]
Could you please checksum the token addresses

**Comment by JRDNBLFRT** [comment]
Yes, it's correct!

**Comment by lukebogtools** [comment]
Hey JRDNBLFRT, What we mean is that you need to rename the folder: 0xe59d382ebfa8034b35e8f51a01a2546d7cfab23f to 0xe59D382eBfA8034b35e8f51A01a2546d7CFAb23F  (notice the capitalisation.)

Cheers,
Luke

**Comment by JRDNBLFRT** [comment]
I am sorry! First time, must be a big noob....

**Comment by JRDNBLFRT** [comment]
Really don't know if it's ok now?

**Pull request merged**
