### PR TITLE
checksum format

### PR DESCRIPTION
**Pull request by CamistryCam**
bsc/asset/0xD99D4C01063b7aC970577E29DE8B958D5392C952/logo.png

### CODE REVIEW

**Comment by CamistryCam** [comment]
Bogged Finance (256 x 256 px)

**Comment by CamistryCam** [comment]
Please Upload The logo

**Comment by CamistryCam** [comment]
@lukebogtools please upload logo for Bogged Finance and Trust wallet (We have met the criteria to not have to pay the .5BNB I belive) Thanks :)

**Comment by lukebogtools** [comment]
Hi, this is not correctly submitted. Please look at the instructions or have your developer submit the token info.

**Pull request closed without merging**
