### PR TITLE
adding token

### PR DESCRIPTION
**Pull request by tom-bowern**
Adding Arigato to token list

### CODE REVIEW

**Comment by lukebogtools** [comment]
Hi There,
Please rename the address to the checksum format. https://ethsum.netlify.app/

**Comment by tom-bowern** [comment]
Hi luke,

do we do this even if we are BEP20? it mentioned on the site this is for eth

**Comment by tom-bowern** [comment]
do we do this even if we are BEP20? it mentioned on the site this is for eth

**Comment by tom-bowern** [comment]
@lukebogtools Thanks Luke, this should be resolved now!

**Pull request merged**
