### PR TITLE
Added Gain Protocol

### PR DESCRIPTION
**Pull request by matanelgabsi**
Added Gain Protocol.
Chart is referenced (a long time ago) on telegram (/charts).

Thanks!

### CODE REVIEW

**Comment by matanelgabsi** [comment]
Also added Bogged bot exclusively for our group.
@lukebogtools can we merge this please?

Thanks!

**Comment by matanelgabsi** [comment]
Any news? We have bogged in our telegram, Are we missing something to get this merged?
@lukebogtools

**Comment by lukebogtools** [comment]
Hi, My apologies for the delay. This token is missing the address in a checksum'd format for the folder.

**Comment by lukebogtools** [comment]
Please resubmit with the correction and I'll get this merged

**Comment by matanelgabsi** [comment]
So sorry about that! I was sure I did that, probably a missed copy-paste on my behalf.
Now fixed, thank you!
@lukebogtools

**Pull request merged**
