### PR TITLE
add Micro Bitcoin token

### PR DESCRIPTION
**Pull request by mbitcoin-dev**

### CODE REVIEW

**Comment by mbitcoin-dev** [comment]
@lukebogtools 
 https://bscscan.com/tx/0xd67d9d14eeb68151d005d87c321496bfa599e1469ee5fff8ae6a92af31f0c829

**Comment by lukebogtools** [comment]
Can you rename the folder the files are in to be the checksumed address. (Partial capitalisation)

https://ethsum.netlify.app/

Thanks :)

**Comment by mbitcoin-dev** [comment]
> Can you rename the folder the files are in to be the checksumed address. (Partial capitalisation)
> 
> https://ethsum.netlify.app/
> 
> Thanks :)

Could you take a look the folder name again, it's already the checksummed address.
```
bsc/assets/0xe77011ed703ed06927dBd78e60c549baBAbF913e/info.json
bsc/assets/0xe77011ed703ed06927dBd78e60c549baBAbF913e/logo.png
```

image

**Comment by lukebogtools** [comment]
My bad! Merged

**Pull request merged**
