### PR TITLE
Pull request to add the MTDR Token

### PR DESCRIPTION
**Pull request by matadortoken**

### CODE REVIEW

**Comment by matadortoken** [comment]
@lukebogtools linked in matadortoken.com. Admin said payment was worked out. Can you confirm.

**Comment by lukebogtools** [comment]
Hey, sorry for the delay. We've been underwater with our relaunch. Merged! :)

**Comment by matadortoken** [comment]
Congrats and ty!

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by matadortoken** [comment]
Can you put me in the right way to advertise with you?

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
