### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by krammer88**

### CODE REVIEW

**Comment by krammer88** [comment]
@lukebogtools

**Comment by krammer88** [comment]
@lukebogtools

**Comment by lukebogtools** [comment]
Hey, thanks so much. 

You need to put the info.json file in a folder named after the checksum'd address. Please open a new pull request with that in that format, there is a guide on the README file. Cheers

**Comment by krammer88** [comment]
Luke,

Thank you for your response.

I am very new to Github & Visual Studio Code.

Does the readme file explain how to create a folder?


Thank you,


Kenneth Rammer
***@***.***
732-800-8624

**Pull request closed without merging**
