### PR TITLE
added fetusdoge

### PR DESCRIPTION
**Pull request by amajewski5c**

### CODE REVIEW

**Comment by amajewski5c** [comment]
@lukebogtools bogged chart is already integrated into telegram, regarding  `Processing Fee for tokens which link to their BoggedChart on their Telegram (whether that's in their bot, or in the description) and Website: FREE!`

**Comment by amajewski5c** [comment]
@lukebogtools is this submission in order?

**Comment by lukebogtools** [comment]
Thanks so much, merged :)

**Comment by amajewski5c** [comment]
Awesome thanks!

**Pull request merged**
