### PR TITLE
GAP Pull Request

### PR DESCRIPTION
**Pull request by gapbsc**
Submitted information for BOGGED. We link to the chart from both website and telegram

### CODE REVIEW

**Comment by gapbsc** [comment]
@lukebogtools Just wanted to let you know that we are linking to bogged charts from both the website, telegram description and telegram bot :)

**Comment by lukebogtools** [comment]
Hey, thanks so much. 

You just need to make one change, can you please change the address in the folder name to the checksum'd address (with capitalisation). You can find the checksum'd address by pasting it here: https://ethsum.netlify.app/

Tag me once it's done and I'll get this merged :)

**Comment by gapbsc** [comment]
@lukebogtools Sorry about that. Directory name has been updated to checksum format!

**Comment by gapbsc** [comment]
All fixed! Sorry about that!

On 2021-06-16 08:58, Luke Martinez wrote:

> Hey, thanks so much. 
> 
> You just need to make one change, can you please change the address in the folder name to the checksum'd address (with capitalisation). You can find the checksum'd address by pasting it here: https://ethsum.netlify.app/ 
> 
> Tag me once it's done and I'll get this merged :) 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/BogTools/Bogged-Token-List/pull/144#issuecomment-862318014
[2]

**Pull request merged**
