### PR TITLE
Add BNB-MAX.COM BNBMAX

### PR DESCRIPTION
**Pull request by managerbnbmax**

### CODE REVIEW

**Comment by managerbnbmax** [comment]
Hi @LukeBogTools

tx confirmation : https://bscscan.com/tx/0xeef685a7c25182e51daadfcc82355e2cc2804b2f2e5ebce2cf221c0bbebb728e

Thanks guys

**Comment by lukebogtools** [comment]
Hey, thanks so much. 

You just need to make one change, can you please change the address in the folder name to the checksum'd address (with capitalisation). You can find the checksum'd address by pasting it here: https://ethsum.netlify.app/

Tag me once it's done and I'll get this merged :)

**Comment by managerbnbmax** [comment]
Hi @lukebogtools,

Thanks for your feedback, 
I did it 

Thanks

**Comment by managerbnbmax** [comment]
dONE

Le 2021-06-16 07:57, Luke Martinez a écrit :

**Pull request merged**
