### PR TITLE
Adding AiChain Logo

### PR DESCRIPTION
**Pull request by aujla0991**
Email: info@aichain.pro

### CODE REVIEW

**Comment by aujla0991** [comment]
@lukebogtools Tx: 0x3a3bd9eb53dda190626670f37bd9050d53c06f3012f8bb5bd8d537beda2e76e1

**Comment by aujla0991** [comment]
@lukebogtools https://bscscan.com/tx/0x3a3bd9eb53dda190626670f37bd9050d53c06f3012f8bb5bd8d537beda2e76e1

**Comment by TheAiChain** [comment]
@lukebogtools  Please let us know if you have any updates on this :) thank you

**Comment by lukebogtools** [comment]
Hey, my apologies. We'll get this merged now.

**Pull request merged**
