### PR TITLE
Add Bevo Token

### PR DESCRIPTION
**Pull request by pippinmole**

### CODE REVIEW

**Comment by pippinmole** [comment]
@lukebogtools https://bscscan.com/tx/0x05e5e7baceb9582f509b7063516130408742ddcc8e99405d323315373113997a

**Comment by pippinmole** [comment]
@lukebogtools bump

**Comment by lukebogtools** [comment]
Hey, can you edit the folder name to use the checksum'd address? YOu can generate the checksum'd address ( with capitalisation) on this site: https://ethsum.netlify.app/

**Comment by lukebogtools** [comment]
Sorry for the delay :) Let me know when that's sorted

**Comment by pippinmole** [comment]
@lukebogtools Sorted.

**Pull request merged**
