### PR TITLE
Create info.json

### PR DESCRIPTION
**Pull request by LevelUPBNB**

### CODE REVIEW

**Comment by LevelUPBNB** [comment]
LevelUP - BNB uses Waterfall bot in telegram for the price, this automatically used the Bogged Chart so no payment will need to be made. https://t.me/Levelupbnb

Thanks, any information then let me know

@lukebogtools

**Comment by lukebogtools** [comment]
Hey, thanks so much. Just need to make one change, can you please change the address in the folder name to the checksum'd address (with capitalisation). https://ethsum.netlify.app/

**Comment by LevelUPBNB** [comment]
Sorry @lukebogtools it should be on the BSC - not ETH. what do I need to change the address in folder name to? Thanks for your help

**Comment by LevelUPBNB** [comment]
Hi @lukebogtools do you have the information to add us now? I sent again with it Checksummed. Thanks in advance

**Pull request closed without merging**
