### PR TITLE
Adding RAPTOR

### PR DESCRIPTION
**Pull request by ygboucherk**
Hello, 

We're interested in adding our token (RAPTOR) there. 

Is it possible and how much would it cost ?

Thanks very much !

### CODE REVIEW

**Comment by lukebogtools** [comment]
Hey, it's free if you link to our charts from your website. :)

**Comment by lukebogtools** [comment]
When you have a chance, can you edit the folder name to 

"0xf9A3FdA781c94942760860fc731c24301c83830A"

It needs to be checksum'd to work correctly :)

**Comment by ygboucherk** [comment]
Okay I'm checksuming address

**Comment by ygboucherk** [comment]
hmm I renamed directory

**Comment by lukebogtools** [comment]
Merging now, please do link to your chart from your website when you have a  chance.

Kind regards,
Luke
BogTools

**Comment by ygboucherk** [comment]
Okay, thanks very much !

**Comment by ygboucherk** [comment]
If we have problems putting the chart, I'll get some bnb for paying the 0.5 bnb fee !

**Comment by ygboucherk** [comment]
hmm is pancakeswap v2 support planned (or already implemented somewhere on the website) ?
We have already migrated most of liquidity to pancakeswap v2 !

**Comment by lukebogtools** [comment]
It will be released in a few hours. :)

**Pull request merged**
