### PR TITLE
Addeding Alchemist Defi Token Assets MIST and AURUM

### PR DESCRIPTION
**Pull request by Alchemist-defi**
Hi John, 

Our ecosystem has two tokens MIST and AURUM as such ive added both in the pull request. 

We link directly to your charts site from our site for all our pricing data. Does that suffice with regards to the fee waiver?

### CODE REVIEW

**Comment by Alchemist-defi** [comment]
@lukebogtools John requested that I tag you once complete. Thanks for your consideration.

**Comment by JohnBogTools** [comment]
Could you please checksum the MIST address

**Comment by lukebogtools** [comment]
Hi Alchemist,
You need to rename the logo files to logo.png

and ensure you're using the checksum'd (capitalised) token address.  You can enter your token address here to get the checksum'd version: https://ethsum.netlify.app/

Let me know once this is done and we'll merge this request.

**Comment by Alchemist-defi** [comment]
@lukebogtools @JohnBogTools thanks guys. 
Made the updates you requested.

**Comment by lukebogtools** [comment]
Thanks, merged :)

**Comment by Alchemist-defi** [comment]
> 
> 
> Thanks, merged :)

Did i do something wrong with the MIST uploads? I see logo's are displaying? 

https://charts.bogged.finance/?token=0x6f8FE12CC34398d15b7D5A5BA933E550DA1D099f

**Pull request merged**
