### PR TITLE
Add DYOR token

### PR DESCRIPTION
**Pull request by bretep**

### CODE REVIEW

**Comment by bretep** [comment]
@lukebogtools

https://bscscan.com/tx/0x46c008dfdef2c61329f4bdf7da073089654560865f9cac57ad71063a89ad7722


Thank you!

**Comment by bretep** [comment]
@lukebogtools 0x46c008dfdef2c61329f4bdf7da073089654560865f9cac57ad71063a89ad7722

**Comment by bretep** [comment]
Hi, @lukebogtools hope you are doing well. We sent in the BNB a while ago and are looking for an update. 

Is there anything that concerns you or I need to fix?

https://bscscan.com/tx/0x46c008dfdef2c61329f4bdf7da073089654560865f9cac57ad71063a89ad7722

**Comment by chuckierave** [comment]
@lukebogtools wondering if we could get an update on this?

Thanks

**Comment by lukebogtools** [comment]
My apologies for the delay, this is now merged

**Pull request merged**
