### PR TITLE
added in hoge finance logo

### PR DESCRIPTION
**Pull request by matthewPrimitive**
Created the folder for Hoge Finance

### CODE REVIEW

**Review by zeroturningback — CHANGES_REQUESTED** [review]
[Diamonds are Forever](0x8fb1a59ca2d57b51e5971a85277efe72c4492983)

**Review by zeroturningback — CHANGES_REQUESTED** [review]
bsc/_minicharts/0x8fb1a59ca2d57b51e5971a85277efe72c4492983.png

**Comment by matthewPrimitive** [comment]
@zeroturningback What are suggesting to change

**Comment by lukebogtools** [comment]
Your pull request includes changes to protected files, please only include the relevant files in your pull request.

**Pull request closed without merging**
